#!/bin/sh
DOTFILESDIR="$HOME/.dotfiles"
export LC_ALL="en_US.UTF-8"

git config --replace-all core.worktree "$HOME"

cd "$DOTFILESDIR" || exit
git pull
git submodule init
git submodule update --remote

cd powerline || exit
pip install -e .
fc-cache -vf ~/.fonts/

cd "$HOME" || exit
touch .z
