#!/bin/bash
DOTFILESDIR=$(cd "$(dirname "$0")"/..; pwd)

cd "$HOME" || exit
for F in $(ls -A "$DOTFILESDIR"); do
  if [[ -L "$F" ]]; then
    rm "$F"
    mv "$DOTFILESDIR/$F" $F
  fi
done

mv "$DOTFILESDIR" "$HOME/.dotfiles"
echo "gitdir: ../../.dotfiles/.git/modules/oh-my-zsh" > .zsh/oh-my-zsh/.git

git config --replace-all core.worktree "$HOME"
mv .dotfiles/.gitmodules .
rm -rf .vim*

sed -i 's#worktree \?= \?#worktree = ../#' .dotfiles/.git/modules/oh-my-zsh/config
