#!/bin/env bash
# Spawn a shell in a temp dir and rm it afterwards

TMPSH_DIR="$(mktemp -d -p /tmp)"
cd "$TMPSH_DIR" || exit 1

if [ -z $1 ]; then
  $SHELL
else
  "$@"
fi

cd /tmp || exit 1
rm -rf "$TMPSH_DIR"
