#!/usr/bin/env sh
DOTFILESDIR="$HOME/.dotfiles"
export LC_ALL="en_US.UTF-8"

cd "$DOTFILESDIR" || exit
export GIT_DIR="$DOTFILESDIR/.git"
git pull --no-rebase --ff-only
unset GIT_DIR

nix-env -f '<nixos>' -iA userPackages

tmux source-file ~/.tmux.conf

