#!/usr/bin/env sh
DOTFILESDIR="$HOME/.dotfiles"
export LC_ALL="en_US.UTF-8"

cd "$DOTFILESDIR" || exit
export GIT_DIR="$DOTFILESDIR/.git"
git pull --no-rebase --ff-only
git submodule init
git submodule update --remote
unset GIT_DIR

$DOTFILESDIR/nvim/nvim-plugins.sh $DOTFILESDIR/nvim/nvim-plugins.json
nix-build $DOTFILESDIR/zsh/conf.nix --out-link $DOTFILESDIR/zsh/result
nix-env -f '<nixos>' -iA userPackages

tmux source-file ~/.tmux.conf

