#!/bin/sh
DOTFILESDIR="$HOME/.dotfiles"
export LC_ALL="en_US.UTF-8"

cd "$DOTFILESDIR" || exit
export GIT_DIR="$DOTFILESDIR/.git"
git pull --no-rebase --ff-only
git submodule init
git submodule update --remote

tmux source-file ~/.tmux.conf
