#export TERM=screen-256color
# Auto-tmux
if [ "$PS1" != "" -a -z "$TMUX" ]; then
    command -v tmux 2>&1 && ((tmux ls | grep -vq attached && tmux at) || tmux new-session) && exit 0
    echo "Tmux failed! continuing with normal startup"
else
    [[ -f /var/run/motd.dynamic ]] && cat /var/run/motd.dynamic
fi

ZSH_DIR=$HOME/.zsh

umask 027

# Basic setup
HISTFILE=$ZSH_DIR/history
HISTORY_BASE=$ZSH_DIR/per-dir-history
ZSH_CACHE_DIR=$ZSH_DIR/cache
HIST_STAMPS="yyyy-mm-dd"
HISTSIZE=100000
SAVEHIST=100000

# Oh-my-zsh
plugins=(colorize colored-man git per-directory-history rsync systemd)

ZSH_THEME="ys"

# Autocompletion
setopt extendedglob
setopt NO_HUP
unsetopt list_ambiguous
bindkey -e

zstyle :compinstall filename "$HOME/.zshrc"
CORRECT_IGNORE='_*'

# fpath=(~/.zsh/completion $fpath)
# autoload -Uz compinit && compinit -i
# _comp_options+=(globdots)

# export ZSH_CUSTOM="$HOME/.zsh"
source ~/.dotfiles/zsh/result
autoload -Uz compinit && compinit

CASE_SENSITIVE="false"
# ENABLE_CORRECTION="true"
COMPLETION_WAITING_DOTS="true"
ZSH_HIGHLIGHT_HIGHLIGHTERS=(main brackets)
typeset -A ZSH_HIGHLIGHT_STYLES
ZSH_HIGHLIGHT_STYLES[globbing]='none'


# User configuration
#
DISABLE_UNTRACKED_FILES_DIRTY="true"

#autoload -U up-line-or-beginning-search down-line-or-beginning-search
#zle -N up-line-or-beginning-search down-line-or-beginning-search
#bindkey '^[[A' up-line-or-beginning-search
#bindkey '^[[B' down-line-or-beginning-search

#autoload zkbd
bindkey "${terminfo[kcuu1]}" history-beginning-search-backward
bindkey "${terminfo[kcud1]}" history-beginning-search-forward


function mk_prompt {
    function pwrl_helper() {python3 $HOME/.dotfiles/powerline-helper.py zsh '#' "$1"}
    function git_prompt_info() {
      ref=$(git symbolic-ref HEAD 2> /dev/null)
      if [ $? -eq 0 ]; then
        pwrl_helper "B240##F250,B238# ${ref#refs/heads/} #"
      else
        pwrl_helper "B240##"
      fi
    }

    PROMPT=$'\n'
    PROMPT=$PROMPT$(pwrl_helper '
      F250,B240# %M #
      F250,B238# %(!.%{'$fg[red]'%}.)%n #
      F15,B31,bold# %~ #
      F250,B240# %* ')
    PROMPT=$PROMPT'$(git_prompt_info)'
    PROMPT=$PROMPT$'\n'
    PROMPT=$PROMPT$(pwrl_helper 'B236#%{%(?:'$fg_bold[green]':'$fg_bold[red]')%} $ #')
    PROMPT=$PROMPT' '

}
mk_prompt

source $ZSH_DIR/aliases
source $ZSH_DIR/proxy

export PATH="$HOME/.bin:$HOME/.local/bin:$PATH"
export EDITOR="nvim"
export FZF_DEFAULT_COMMAND='ag -g ""'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
_fzf_compgen_path() {
  ag -g "" "$1"
}

